name: canopy_quality_model
url: https://github.com/johnfrancis13/canopy-quality-scivision
import: canopy_quality
model: treenet_rgb
prediction_fn:
    call: predict
    args:
        X: np_image
    kwargs:
        batch_size: 1

