name: canopy_quality_model
url: https://github.com/johnfrancis13/canopy-quality-scivision
import: canopy_quality
model: treenet
args:
    label_level: label3_detritus
prediction_fn:
    call: predict
    args:
        X: image
    kwargs:
        batch_size: 1


