name: canopy_quality_model
url: .scivision/model.yaml
import: canopy_quality
model: treenet
args:
    model_name: rgb
prediction_fn:
    call: predict
    args:
        X: image
    kwargs:
        batch_size: 1


